name: greet-based-on-input
description: 'Greet someone'

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.rng-number.outputs.random-number }}

runs:
  using: "composite"
  steps:
    - id: rng-number
      run: echo "Generated Number $(echo $RANDOM)" >> $GITHUB_OUTPUT    # we mappen het gegenereerde getal naar de output variabele
      shell: bash


    # - run: echo "Hello ${{ inputs.who-to-greet }}"
    #   shell: bash



    # - run: echo "Hello ${{ inputs.who-to-greet }}"
    #   shell: bash


  #   inputs:
  # who-to-greet:  
  #   description: 'Who to greet'
  #   required: true
  #   default: 'Tim'