name: run-shell-script
description: 'Run a shell script'

runs:
  using: "composite"
  steps:

    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH    ## kijk of dit nodig is voor de shell te kunnen runnen... 
      shell: bash

    - run: tims-script.sh
      shell: bash

    - name: Make Second Script Executable
      run: chmod +x second-script.sh
      shell: bash

    - run: second-script.sh
      shell: bash

    # - run: echo "Hello ${{ inputs.who-to-greet }}"
    #   shell: bash


    # - id: tim-bragging
    #   run: echo "concrete-brag=Tim Is Slim" >> $GITHUB_OUTPUT    # we mappen het gegenereerde getal naar de output variabele
    #   shell: bash

    # - run: echo "Hello ${{ inputs.who-to-greet }}"
    #   shell: bash



# outputs:
#   tim-likes-to-brag:
#     description: "Return Some Text As Demo"
#     value: ${{ steps.tim-bragging.outputs.concrete-brag }}

  #   inputs:
  # who-to-greet:  
  #   description: 'Who to greet'
  #   required: true
  #   default: 'Tim'