name: greet-based-on-input
description: 'Greet someone'

runs:
  using: "composite"
  steps:
    - run: echo "Hello Tim"
      shell: bash



# inputs:
#   who-to-greet:  
#     description: 'Who to greet'
#     required: true
#     default: 'Tim'


    # - run: echo "Hello ${{ inputs.who-to-greet }}"
    #   shell: bash